# Generated by Django 5.0.6 on 2024-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follower_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
