# Generated by Django 5.0.6 on 2024-08-20 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
